-- MySQL Script generated by MySQL Workbench
-- Thu Oct 27 18:47:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MyUnify
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MyUnify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS MyUnify;
USE MyUnify ;

-- -----------------------------------------------------
-- Tabla Creador
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Creador(
  id_creador INT NOT NULL,
  nombre_creador CHAR(60) NOT NULL,
  PRIMARY KEY (id_creador));


-- -----------------------------------------------------
-- Tabla Usuario
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Usuario (
  Creador_id_creador INT NOT NULL,
  Fraternidad_Creador_id_creador INT NULL,
  apodos CHAR(45) NOT NULL,
  clave CHAR(25) NOT NULL,
  correo CHAR(60) NOT NULL,
  instagram CHAR(30) NOT NULL,
  importancia INT NOT NULL,
  PRIMARY KEY (Creador_id_creador),
--   INDEX fk_Usuario_Creador1_idx (Creador_id_creador ASC) VISIBLE,
--  INDEX fk_Usuario_Fraternidad1_idx (Fraternidad_Creador_id_creador ASC) VISIBLE,
--  CONSTRAINT fk_Usuario_Creador1
    FOREIGN KEY (Creador_id_creador)
    REFERENCES MyUnify.Creador (id_creador)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_Usuario_Fraternidad1
    FOREIGN KEY (Fraternidad_Creador_id_creador)
    REFERENCES MyUnify.Fraternidad (Creador_id_creador)
    ON DELETE CASCADE  ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Tabla Fraternidad
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Fraternidad (
  Creador_id_creador INT NOT NULL,
  jefe Usuario_Creador_id_creador INT NOT NULL,
  descripcion TEXT(120) NOT NULL,
  nombre CHAR(45) NOT NULL,
  PRIMARY KEY (Creador_id_creador),
 -- INDEX fk_Fraternidad_Creador_idx (Creador_id_creador ASC) VISIBLE,
 -- INDEX fk_Fraternidad_Usuario1_idx (jefe Usuario_Creador_id_creador ASC) VISIBLE,
 -- CONSTRAINT fk_Fraternidad_Creador
    FOREIGN KEY (Creador_id_creador)
    REFERENCES MyUnify.Creador(id_creador)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
 -- CONSTRAINT fk_Fraternidad_Usuario1
    FOREIGN KEY (jefe Usuario_Creador_id_creador)
    REFERENCES MyUnify.Usuario (Creador_id_creador)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table LUGAR
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Lugar (
  id_lugar INT NOT NULL,
  aforo INT NOT NULL,
  direccion CHAR(80) NOT NULL,
  nombre CHAR(80) NOT NULL,
  PRIMARY KEY (id_lugar));


-- -----------------------------------------------------
-- Table MyUnify.Notificacion
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Notificacion (
  id_notificacion INT NOT NULL,
  estado TINYINT NOT NULL,
  tipo CHAR(50) NOT NULL,
  PRIMARY KEY (id_notificacion));


-- -----------------------------------------------------
-- Table MyUnify.Evento
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Evento (
  id_evento INT NOT NULL,
  Notificacion_id_notificacion INT NOT NULL,
  Creador_id_creador INT NOT NULL,
  Lugar_id_lugar INT NOT NULL,
  nombre CHAR(80) NOT NULL,
  descripcion TEXT(150) NULL DEFAULT 'Severo evento, caiga',
  hora INT NOT NULL,
  fecha DATE NOT NULL,
  facultad CHAR(80) NULL,
  PRIMARY KEY (id_evento),
 -- INDEX fk_Evento_Creador1_idx (Creador_id_creador ASC) VISIBLE,
 -- INDEX fk_Evento_Lugar1_idx (Lugar_id_lugar ASC) VISIBLE,
 -- INDEX fk_Evento_Notificacion1_idx (Notificacion_id_notificacion ASC) VISIBLE,
 -- CONSTRAINT fk_Evento_Creador1
    FOREIGN KEY (Creador_id_creador)
    REFERENCES MyUnify.Creador (id_creador)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
 -- CONSTRAINT fk_Evento_Lugar1
    FOREIGN KEY (Lugar_id_lugar)
    REFERENCES MyUnify.Lugar (id_lugar)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
 -- CONSTRAINT fk_Evento_Notificacion1
    FOREIGN KEY (Notificacion_id_notificacion)
    REFERENCES MyUnify.Notificacion (id_notificacion)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table MyUnify.Pregunta
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Pregunta (
  id_pregunta INT NOT NULL,
  Evento_id_evento INT NOT NULL,
  remitente Usuario_Creador_id_creador INT NOT NULL,
  contenido TEXT(120) NOT NULL,
  PRIMARY KEY (id_pregunta),
 -- INDEX fk_Pregunta_Usuario1_idx (remitente Usuario_Creador_id_creador ASC) VISIBLE,
 -- INDEX fk_Pregunta_Evento1_idx (Evento_id_evento ASC) VISIBLE,
 -- CONSTRAINT fk_Pregunta_Usuario1
    FOREIGN KEY (remitente Usuario_Creador_id_creador)
    REFERENCES MyUnify.Usuario (Creador_id_creador)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  -- CONSTRAINT fk_Pregunta_Evento1
    FOREIGN KEY (Evento_id_evento)
    REFERENCES MyUnify.Evento (id_evento)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table MyUnify.Respuesta
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Respuesta (
  id_respuesta INT NOT NULL,
  Pregunta_id_pregunta INT NOT NULL,
  remitente Usuario_Creador_id_creador INT NOT NULL,
  contenido TEXT(120) NOT NULL,
  PRIMARY KEY (id_respuesta, Pregunta_id_pregunta),
 -- INDEX fk_Respuesta_Pregunta1_idx (Pregunta_id_pregunta ASC) VISIBLE,
 -- INDEX fk_Respuesta_Usuario1_idx (remitente Usuario_Creador_id_creador ASC) VISIBLE,
 -- CONSTRAINT fk_Respuesta_Pregunta1
    FOREIGN KEY (Pregunta_id_pregunta)
    REFERENCES MyUnify.Pregunta (id_pregunta)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  --CONSTRAINT fk_Respuesta_Usuario1
    FOREIGN KEY (remitente Usuario_Creador_id_creador)
    REFERENCES MyUnify.Usuario (Creador_id_creador)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table MyUnify.Etiqueta
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Etiqueta (
  id_etiqueta INT NOT NULL,
  descripcion TEXT(120) NOT NULL,
  PRIMARY KEY (id_etiqueta))
;


-- -----------------------------------------------------
-- Table MyUnify.EventoEtiqueta
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS EventoEtiqueta (
  Evento_id_evento INT NOT NULL,
  Etiqueta_id_etiqueta INT NOT NULL,
  PRIMARY KEY (Evento_id_evento, Etiqueta_id_etiqueta),
 -- INDEX fk_Evento_has_Etiqueta_Etiqueta1_idx (Etiqueta_id_etiqueta ASC) VISIBLE,
 -- INDEX fk_Evento_has_Etiqueta_Evento1_idx (Evento_id_evento ASC) VISIBLE,
 -- CONSTRAINT fk_Evento_has_Etiqueta_Evento1
    FOREIGN KEY (Evento_id_evento)
    REFERENCES MyUnify.Evento (id_evento)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
 -- CONSTRAINT fk_Evento_has_Etiqueta_Etiqueta1
    FOREIGN KEY (Etiqueta_id_etiqueta)
    REFERENCES MyUnify.Etiqueta (id_etiqueta)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table MyUnify.EtiquetaUsuario
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS EtiquetaUsuario (
  Etiqueta_id_etiqueta INT NOT NULL,
  Usuario_Creador_id_creador INT NOT NULL,
  PRIMARY KEY (Etiqueta_id_etiqueta, Usuario_Creador_id_creador),
 -- INDEX fk_Etiqueta_has_Usuario_Usuario1_idx (Usuario_Creador_id_creador ASC) VISIBLE,
 -- INDEX fk_Etiqueta_has_Usuario_Etiqueta1_idx (Etiqueta_id_etiqueta ASC) VISIBLE,
 -- CONSTRAINT fk_Etiqueta_has_Usuario_Etiqueta1
    FOREIGN KEY (Etiqueta_id_etiqueta)
  --  REFERENCES MyUnify.Etiqueta (id_etiqueta)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
 -- CONSTRAINT fk_Etiqueta_has_Usuario_Usuario1
    FOREIGN KEY (Usuario_Creador_id_creador)
    REFERENCES MyUnify.Usuario (Creador_id_creador)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table MyUnify.UsuarioNotificacion
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS UsuarioNotificacion (
  Usuario_Creador_id_creador INT NOT NULL,
  Notificacion_id_notificacion INT NOT NULL,
  PRIMARY KEY (Usuario_Creador_id_creador, Notificacion_id_notificacion),
 -- INDEX fk_Usuario_has_Notificacion_Notificacion1_idx (Notificacion_id_notificacion ASC) VISIBLE,
 -- INDEX fk_Usuario_has_Notificacion_Usuario1_idx (Usuario_Creador_id_creador ASC) VISIBLE,
 -- CONSTRAINT fk_Usuario_has_Notificacion_Usuario1
    FOREIGN KEY (Usuario_Creador_id_creador)
    REFERENCES MyUnify.Usuario (Creador_id_creador)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
 -- CONSTRAINT fk_Usuario_has_Notificacion_Notificacion1
    FOREIGN KEY (Notificacion_id_notificacion)
    REFERENCES MyUnify.Notificacion (id_notificacion)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table MyUnify.Amigos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Amigos (
  Usuario_Creador_id_creador INT NOT NULL,
  Usuario_Creador_id_creador1 INT NOT NULL,
  PRIMARY KEY (Usuario_Creador_id_creador, Usuario_Creador_id_creador1),
--  INDEX fk_Usuario_has_Usuario_Usuario2_idx (Usuario_Creador_id_creador1 ASC) VISIBLE,
--  INDEX fk_Usuario_has_Usuario_Usuario1_idx (Usuario_Creador_id_creador ASC) VISIBLE,
--  CONSTRAINT fk_Usuario_has_Usuario_Usuario1
    FOREIGN KEY (Usuario_Creador_id_creador)
    REFERENCES MyUnify.Usuario (Creador_id_creador)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
--  CONSTRAINT fk_Usuario_has_Usuario_Usuario2
    FOREIGN KEY (Usuario_Creador_id_creador1)
    REFERENCES MyUnify.Usuario (Creador_id_creador)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
;


